### ISSUE TITLE
User should be aware on how to fix errors!

### ISSUE THREAD

**Issue by Murii** [Sponk/NeoEditor#164]
int setWidgetPosition()
{
MScriptContext* script = NeoEngine::getInstance()->getScriptContext();

//We should tell the user what is wrong!
if(script->getArgsNumber() != 2)
return 0;

Widget* w = GuiSystem::getInstance()->getWidget(script->getInteger(0));

MVector2 vec;
script->getFloatArray(1, vec, 2);
w->setPosition(vec);

return 1;
}

**Comment by Sponk** [comment]
To fix this it would be best to move the "isFunctionOk" function from ScriptApi.cpp to the MScriptContext class or the Neo::LuaScript class so it can be called any time it is needed.

The preferred way would be to make a pure virtual method in MScriptContext and then implement this behavior in Neo::LuaScript. This is necessary since this method depends on the logging system that is not accessible in the core library.
