### ISSUE TITLE
Ubershader

### ISSUE THREAD

**Issue by Akira1San** [Sponk/NeoEditor#247]
Ubershader
Creating a completely customizable material editor could take too long to develop. So i propose a ubershader approach. As from the beginning there could be a simple ubershader in the material editor.
It could have like: Diffuse; Spec; Normal; Reflect slots for adding textures and some parameters/sliders to adjust the settings. when adjust them, next step would be the press the button create shader.
The shaders even could use OGL 3.2 since most users got atleast intel hd 4000, that supports ogl 3.3. Looks like OGL 3.2 supports Subroutines unless if im mistaken.  
Links to read.
http://gamedev.stackexchange.com/questions/57957/game-engine-design-ubershader-shader-management-design
http://stackoverflow.com/questions/30581719/opengl-glsl-uniform-branching-vs-multiple-shaders
http://hacksoflife.blogspot.bg/2009/02/uber-shaders-evolution-or-optimization.html
http://www.sunandblackcat.com/tipFullView.php?l=eng&topicid=20

**Comment by ypflanzer** [comment]
The current work on rendering concerns mainly a deferred rendering approach which is based on per-project shaders so an "Übershader" basically already implemented. You can start modifying shading right now if you wish to.

The problem that arises is that you probably meant a per-object shader.
Those do not fit well with the deferred rendering approach since there is no clean and scalable way to determine which shader has to be used for which fragment on the screen. That means every customized shader has to be rendered in the forward pass together with all transparent objects. This way is only feasible if the effect that is desired is vastly different from the default behavior that supports the mentioned diffuse, specular (i.e. roughness now) etc. textures since only this shader can support the advantages of having deferred shading.

The goal is to have the main deferred shader that is flexible enough to deliver all visual results one may want by adjusting parameters without having to resort to custom GLSL code. That doesn't mean that it should be impossible to write custom GLSL code, just that it shouldn't be necessary.

Besides: I found subroutines to work very badly on some drivers. They tend to crash a lot so I have this extension disabled on my machine (which is using either the AMD radeonsi or fglrx driver). All GL3.1+ features used are optional and only used on systems that support them, including the GL_ARB_shader_subroutine extension.

**Comment by Akira1San** [comment]
You can close it now  -solved.
