### ISSUE TITLE
Snap to grid

### ISSUE THREAD

**Issue by Akira1San** [Sponk/NeoEditor#67]
Snap to grid is useful when making a map level.
Snap to grid options:
Meters(x,y) - the Maratis meters on screen. How big should the grid be. (x =1, y=1) would be a meter.
Size(x,y) - The number grid rectangles that fill inside a Meters
Spacing(x,y) The distance between the sizes

**Comment by jamesgeek** [comment]
A simple snap-to-grid functionality would be wonderful. Currently, the exact positioning is still very time consuming because you have to finely adjust the coordinates by hand for each object.
The snap-to-surface in this context would probably a killer-feature, but could also be integrated later.
I guess everyone who works longer with neo-editor will very quickly come to the point where you wants a snap-to-grid functionality.
Whenever I create assets for a new project, the raster precision is the point which always requires the most time. Currently I use Blender for the level design, as you just have to work the fastest there with the snap-to-grid functionality. 
Unfortunately, here are the mesh files (after exporting) sometimes over 100 mb in size, since even a linked copy of an object at a different position is defined as a submesh.
Therefore, I would love to make the level design directly in neo-editor. This would be much more efficient because each object actually refers to only one instance (= mesh).
Maybe you could first implement a very simple snap-to-grid functionality, so at least you can specify a value for the stepwise moving and rotating.
Course only if you can find time for that! :smiley:

**Comment by Sponk** [comment]
I implemented an initial version of this feature. It needs some UI to tweak the snap distance though, I did not find a way to integrate that into the existing toolbar yet.

**Comment by jamesgeek** [comment]
Thank you for the fast implementation! :-)

Because of the toolbar, I would suggest moving the existing transformation and rotation speed values into the Preferences Dialog (perhaps under the cathegory input?). This of course depends on how often the average user needs of these functions. In the current commercial engines such as Unreal Engine 4, Cryengine or Unity 4 those camera-movement-settings are available only through the options or via keyboard shortcuts. The snap distance should be immediately available in addition to the transformation selection! Below is a small example of how the whole thing in the Unreal Engine 4 has been solved (only as inspiration):

https://docs.unrealengine.com/latest/INT/Engine/Actors/Transform/index.html#snapping

**Comment by Sponk** [comment]
I think I will do it this way. And I think I will introduce some sort of dynamic toolbar for Lua plugins to display stuff so the editor is better extensible.

**Comment by ypflanzer** [comment]
The snap to grid UI is now ready for usage. Closing.

**Comment by ypflanzer** [comment]
Re-implementation in the new Neo2D editor.
